### ISSUE TITLE
how to show navigation drawer icon in toolbar 

### ISSUE THREAD

**Issue by ArbazMateen** [rom4ek/ArcNavigationView#10]
how to show navigation drawer icon in toolbar like this
[https://i2.wp.com/lh3.googleusercontent.com/-5IPrgC_gr34/VNT0RzGn_iI/AAAAAAAABL4/EvxrQ3t5M5o/s720/layout_structure_appbar_structure4.png?w=1170&ssl=1](url)

**Comment by romtsn** [comment]
The link is broken. And how does it relate to the library?

**Comment by romtsn** [comment]
Closed as unrelated to the library
