### ISSUE TITLE
ArcNavigationView is not displayed in api 25

### ISSUE THREAD

**Issue by sebamena** [rom4ek/ArcNavigationView#12]
The drawer is not displayed in api 25.

Please Help.

Screenshot: http://prntscr.com/j9j848

**Comment by romtsn** [comment]
But is the normal `NavigationView` displayed correctly though?

**Comment by sebamena** [comment]
Yes, finally i have to remove this lib and use android.support.design.widget.NavigationView

**Comment by romtsn** [comment]
hm, could you post some details maybe about your usage? Maybe sample project on github? So I could take a closer look.
