### ISSUE TITLE
Transparent status/navigation bar

### ISSUE THREAD

**Issue by pietro309** [rom4ek/ArcNavigationView#2]
Hi,

what a great library you made. It is really easy to use and looks pretty awesome. 

I found some UI bug when navigation view is used with transparent navigation bar.

![snimka obrazovky 2017-02-15 o 21 41 38](https://cloud.githubusercontent.com/assets/5663160/22994656/ffe19c2e-f3c7-11e6-9030-bacedf5b9046.png)

**Comment by romtsn** [comment]
Hi there, thanks for trying my library:)
Which android version did you test it? And I also noticed you set a transparent background for ArcNavigationView, right?

**Comment by pietro309** [comment]
Hi, 
I am using Android 6.0.
And this is configuration of my ArcNavigationView:

    <com.rom4ek.arcnavigationview.ArcNavigationView
        android:id="@+id/side_menu"
        android:layout_width="wrap_content"
        android:layout_height="match_parent"
        android:layout_gravity="start"
        android:background="@android:color/white"
        android:fitsSystemWindows="true"
        app:arc_cropDirection="cropInside"
        app:arc_width="96dp"
        app:headerLayout="@layout/sidemenu_header"
        app:itemBackground="@android:color/white"
        app:itemIconTint="#F0D696"
        app:itemTextColor="#3f2712"
        app:menu="@menu/sidemenu_items" />

**Comment by pietro309** [comment]
Hi,

is there any news about this issue? 
When can we expect new release?

Thank for your answer :)

**Comment by romtsn** [comment]
Hello, sir

Unfortunately I don't have time for it right now, but hopefully will try to fix this during this week.
Thanks for using it:)

**Comment by romtsn** [comment]
Fixed in 1.0.3, check this out!
