### ISSUE TITLE
Unexpected behaviours in statusbar 

### ISSUE THREAD

**Issue by LinX64** [rom4ek/ArcNavigationView#3]
Hey man!
Thanks for making this idea into reality.

Anyways, I saw some **unexpected behaviours** in statusbar (like your proof image):

![capture](https://cloud.githubusercontent.com/assets/15968667/23771846/fec4e19e-052d-11e7-8b10-7a88415da132.JPG)

Probably a bug, Right?

Thanks again.

**Comment by romtsn** [comment]
Hi, thanks for the report, will look into this once I have a chance.

**Comment by romtsn** [comment]
Fixed in 1.0.3, check this out
