### ISSUE TITLE
i have problem by rtl direction

### ISSUE THREAD

**Issue by sinadalvand** [rom4ek/ArcNavigationView#9]
how i can make this rtl which arc silde be to left?

**Comment by romtsn** [comment]
This is currently not yet supported. Hopefully will find a possibility to implement it.

**Comment by davidnac** [comment]
Hi,
theres another library that does a similar function, which has solved the rtl problem, maybe you can look at their code to find the way. I like your library more, becaouse you give more customization noptions.
https://github.com/naseemali925/ShapedNavigationView
